---
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
  - npm ci
postRun:
  - node --version
version: 2.0
